- name: install common dependencies
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
   - jq
   - gcc
   - python-pip
   - libffi-devel
   - libselinux-python
   - openssl-devel
   - python
   - python-devel
   - yum-utils

# - name: install ansible, docker-py and docker-compose
#   pip:
#     name: "{{ item.name }}"
#     version: "{{ item.version | default(omit) }}"
#   with_items:
#     - name: pip
#     - name: ansible
#       version: 2.5.3
#     - name: docker-py
#     - name: docker-compose
