- name: install common dependencies
  yum:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
     - jq
     - gcc
     - python-pip
     - libffi-devel
     - libselinux-python
     - openssl-devel
     - python
     - python-devel
     - yum-utils
