- name: remove packet mirror
  file:
    path: /etc/yum.repos.d/packet.repo
    state: absent
  when: provider == 'packet'

- name: install common dependencies
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
   - jq
   - gcc
   - python-pip
   - libffi-devel
   - libselinux-python
   - openssl-devel
   - python
   - python-devel
   - yum-utils

- name: install ansible, docker-py and docker-compose
  pip:
    name: "{{ item.name }}"
    version: "{{ item.version | default(omit) }}"
  with_items:
    - name: pip
      version: 9.0.1
    - name: ansible
      version: 2.4.0.0
    - name: docker-py
      version: 1.10.6
    - name: docker-compose
      version: 1.16.1
