---

- include_tasks: selinux.yml
- include_tasks: dependencies.yml
- include_tasks: yum.yml
- include_tasks: user.yml
- include_tasks: upgrade.yml
- include_tasks: network-manager.yml

- name: ensure lock directory is created
  file: path=/var/lock/subsys state=directory owner=root group=root mode=0755

- name: ensure that postfix is disabled
  service: name=postfix enabled=no state=stopped

- include_tasks: packet.yml
  when: provider == "packet"

- meta: flush_handlers

- name: remove autorelabel
  file:
    path: /.autorelabel
    state: absent
