# Environment variables
env:
  TERRAFORM_VERSION: "0.11.13"
  PACKER_VERSION: "1.3.5"
  RESTIC_VERSION: "0.9.4"
  DOCKER_SCOPE: "testing"

# Enable manage repository scripts
enable:
  - help
  - trust-escapace

# Default script
default: help
