# Environment variables
env:
  TERRAFORM_VERSION: "0.11.8"
  PACKER_VERSION: "1.3.1"
  RESTIC_VERSION: "0.9.3"
  DOCKER_SCOPE: "testing"

# Enable manage repository scripts
enable:
  - help
  - trust-escapace

# Default script
default: help
