sudo: required
language: python
python:
- '3.6'
addons:
  apt:
    packages:
    - bc
services:
- docker
env:
  global:
  - JQ_BINARY="https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64"
  - PATH="/usr/bin:$PATH"
  - AWS_DEFAULT_REGION="us-west-2"
  - TF_VAR_BUILD_NUMBER=${TRAVIS_JOB_NUMBER/./-}
  - secure: GBTo9IB6eDxA3pHpvt+kuKzxr92HmBrPwPqh+YXH7YqtqzwPhekC5jNOWjPogZG5KFLMcsJGtAgqxye33ICyeWKWR4y4q6obIOmq4f984QYBHHmv/Ll0ZwtaD3hy6E9mP8kteazawM+xgipQWE2wMKIUysMTpgqWGVWXqFoeApHCyG8MTJJ4N9Re8D+MuwXJigLZjWqcBbpvSPlCC1qa4cZ2fIxDBl5PdS92ZjUGyN11thDDmF67RFC49r/h6pycHRBG7N/5MQ69XWNZ8ZyBZtdRWooic8wc8sIpo0d/KCQJkTMi1LNs7RxVNo7KYI+Oky/r1B2mMT8gSCzS2wBm2HNl1sJVvYs6X2FAeEHj5SOYLsZMBm0HbHM3m61WZe7SJADWQ9nuddVR3UrFhw+j06gnBstKOdJXtsgxA3A0Nq42NJa8BxM3++FxQgm4OU2reRzW0gVEHFKiz6sNCGwSmcxJxphEK3E0sYKXKPWD2kMn1ERdTfgVrDrLmcby+77m4GXM5kiWJnZ2C5RHUY8ZueIEILHsDgj9VqF955smV/w1sugaJHitUjYyJ/UpD4+Yl0NeSnKb7ljm/9ZvgpHRsPlMGxiSi5y3zeqbf8XTwvJX8C9prLCh1S/lHffu+PERax/Dfa5vwKNJmKalKOJcC6vm4NsCTze/gr/PV6qGOmU=
  - secure: WdM7ZZD+t5/7LUsdGRbj9HalzlpS+n3GsPntU7xzXpQ79vZOlBGqry8OZWo17ES9wINzT3//2g9UyA/ok4vHgj/d93RBw+BSpCohYR4MOgcwpXqq3IF5eRtU5vsTV31ukOlMfSW5epqXF6qvs9B0bA1OYN2EB7F4r/gX2tvAM7mPERXrZ2QGTyz7L+LhiZMQD0G9ARNvycr5K/Qewdi1kkeoyO3zLHvysoXEWy/0E9CdeWr8Matt6QkG1e8cW/AZt0ms/Q70glhif7P8uMVU26rHQ6howTxmU4Sg8ZHMWoNf1z3FJWfjgfe+sq4fyssAQSY5oK0HyvnCe2hF4aTMCZcsZHtzUwpSDtgcHs328PGGr0Q0dg6dMpuCMBNd3P85XyhvBEl7QI4ccc50pW4+szokCSZqai9bPM9n8KCB0ebQUw4+byltEDf1rrXqWfYtDHxfDReePcxNTAM1hmsMvaT+uRa4cJH9XlKWsd8I/LzpV8GX9qtpBw+zct92WP2a9FN+6EaTHwW0edU8GvDnIpD8QOJcYrRBmXtUnBTLiJaa/QrA43YsyN9agr83QkOg/0liX9lQWyXodlr5yXnM99HO/lerCOjP1bszAHsj+0E369WrPx7FGrKOxBZCsMDVIyMGelBJeffYW4jnvdbD7HK/er90u8aMhqmxrmggP6M=
  - secure: nea7ZeMjexMsJEgLz42ms1mg929HHC1eS8cKZXQKqyIuWE1uJFNSAt/wY+heMINYgwfdmjcp+mBTcAA55/0dEkT1eqfRNX725uZdG9dOk9mOdPz1s0KWvp7iu2OakCHxhC5cQe2ddvVTiyq5dADYPzdfUM4rJt0o7DoOpBYSY9BaKXxioJb8vK8jXDofx/1qFql+snblawARUXdQTgOiTQx3/FCmYAIWLh/CboWeNKbWH8bGo+pnnNFkH4WcpxSeRL4wLZz3bkJnTb3sDb5NL3BTgSze44ZUEReXU3b1p6LP1uyBp/o5xGgYEGGYIbQsEORjASaFjJ8IKd8yxJizIIhubpHWotVp73+oeTzbsLzHhbtzMe/BMdsJHulS0xGxgfEE5fMswIKL6aShKm4+kkOrfIewhNvIxGBEi3dAQH71VOjvkxlozX9q+8wOGNZ7ETfq1gwO/+ceF8vrVcU0mfciMoMHiyWVNsz+ZL0nBGdTkaFVA0mgrxre3XyulISgoxVsleSsRtH0yJp+XkPeGOtN2jn6jyk9FmwzAINX6pOcUAWWlBZshcvVDKU4bPRc9PZh16bcauvxkdd6YxMba4mUK+OXggbR2fVATa/B+uUsuRCmcEODFcG/LvE8djF20ch65HzOIYDg9z0eEPGZGEoruySxiNSGAo6VRF4mqqo=
  - secure: MX8OXDdQ1fFOO17vm6j4LerYLvaHcFlIIpCnMASqdB6rmBYONT9nw9Nos4xtKeSWR2sewAzUhF8/wM80vyFxtKFWyJLqfQn0482mJ3vdwRC8yIiMj7hqd9SgV9L1Auk1x5K8eFXeZeo6TTf02oK22Cg+Ki+JY+Hd6WQUjYIODC4oQsMlfaQ5xTXl6VL/MMuZj8xFyKQWTXCR9vnw7qtctJwmk3jP1WxhbihuW9c8OJHWCf6dmn+uEZO4dIP2iU6vPpHKnzgepSKotYNF21PQTGjp7oSKg6MziqJxnd52hmi8OEGxYLY3i8R2sWTtBN49bLAjYdBaL3I96oYhQbSJIUZkW/y2vMPg5psvmwiEvrDNoX1EM2AYYbKxPYAlD3cbIOXZP/48m/RSwurmGTOi1gaSyyVx8EslxMJp8Gt1c9NCSp0RI00BWwXPLcWIltPrLzvoR0ztW1RNwxOwPSYTV3u7KqXBD4T/pR5w18ETrlpnL33y4y8BTNKzMgtaZZok7PPZ5zgPB/Ufuc3ocXHGwoo+d7NSZeRPiF5iLlTizHvtVGyJe5wxqGe289DvUN/+K5NQgq+vnyfGSL79rK/HmlzgWrxJmhopAoYyv42sMBntxTjc+vKI9WPt7w40yj/OABDLOPADho13jD4OuUodSwFI7DVzvDKs4m5E+NOMYWw=
  - secure: FGHr499dclbknOUX87VWCiwG1LnUZmzrMCBRxqUhAdMdrIAAdVV175fqBfpBhulLfTXVLwXYiIadBw1fCc1PlYIJiALyLXuTdWw83eOx+bgm+cCirx+Z3zztO0dPqtmruKW/Zd30wW+zAcMhhv+m9rGHNEVFJIJNCY7xFb/i8gmgBl9NNUUo7VTrPosNICp+N0rRFrXXhVqzeBm3brDIYrS+zEuU5/1OL4i2c125LDKgNmDY6VK/Ghwck3GMlipTKtAhsXNBOuZQ2OVeOdgQQdOK9Ozi7YSEZZteoUBFuothTLBDZ8u7/LZz0Rivum+ggT9A/4L74dnVDTsBu14yc6zxJYPAp+CR6PdDzaQlOEVH6FzObedsQam+isYYe1C12Cl2Fkj1tTgg9LF15RLdlitHZg32sKOLNrMAKMi0/GPPbnocSvTgri8qOlr3Kqoa/lE1xl1llruuzTAAAH6NJOyRue+BV/thhRpRDm7shUJPC3CcOdfg8EFInawiW5/0qlhyZbSeu6QosoGRc1JS2CGET/D9C3mqta9HziPFnaFjCOrn5voQSMy9gM77wt/LXgP9QcoNGnmVsHENAXd4An4BJQ9JxyuEzrAsP3hfUpcFCNNla1g28O0h4gPcRE7iW4pXyFQnx269H+7nTcMpHxIkSn+WLpNkaol4rCRj9fs=
before_install:
- pip install docker ansible==2.7.0 awscli --upgrade
- sudo apt-get update -qq
- sudo apt-get install -y -o Dpkg::Options::="--force-confnew" docker-ce
- mkdir -p ~/bin && curl -sSL -o ~/bin/jq $JQ_BINARY && chmod +x ~/bin/jq
- export PATH=$PATH:~/bin
- "./manage trust-escapace"
- "./manage download-terraform"
- "./manage download-packer"
- "./manage download-restic"
matrix:
  include:
  - env: MODULE="terraform/packet/device.test"
    script: "./manage test-terraform $MODULE"
  - env: MODULE="terraform/aws/fastmail.test"
    script: "./manage test-terraform $MODULE"
  - env: MODULE="terraform/aws/vpc.test"
    script: "./manage test-terraform $MODULE"
  - env: MODULE="terraform/aws/secure-store.test"
    script: "./manage test-terraform $MODULE"
  - env: MODULE="terraform/generic/null-label.test"
    script: "./manage test-terraform $MODULE"
  - env: MODULE="terraform/aws/log-storage.test"
    script: "./manage test-terraform $MODULE"
  - env: MODULE="terraform/aws/spa.test"
    script: "./manage test-terraform $MODULE"
  - env: TEMPLATE="packer/workstation/amazon-ebs.json" TYPE="amazon-ebs"
    script: "./manage test-packer $TEMPLATE $TYPE"
notifications:
  slack:
    secure: cgO75hyhD/gJ9S8C6R/Lox1d0s+2t1DpLOocq9dD4Y4KwfkWMJVSuPM4cG1uUf0RHNvAOhhjnPfwUcFcRttWIjO1CnjvKUPhoktMXcqjDCN7+0JpgSbEOFXpFQs+UpeT+lgEsTow63M88kVQnlTMwuVltqQN8idUShhaSaA0LMJdGnU6OoNrssaZqX28mtPsNRcFBaA00NqXDL8r8YIXy3ILq8zhXOckozUfTjRyrulM94K2zaEGQ4f1KhpBD9fJyju1yvaskWABBXd8foZqDdIKM6IyjbFACnpCYslwCydPUyRnW6tpvfYhjYHc7xEyhImaRASKS+0kBeSZK+zIxrvXBNBjLOEDX8jbzVr5ORAYgcD+S4qL5TlSFBxG4WPQyQv1ysw+Pnc814ztkBFTMB095szy97n6cvE2y7zsg1Jkk6cnXhF7GXqtNm9Zj7se/crb2C1QWhI0jaNrGsEcVwsoPHFk+vavke9Q8++VKmAx8CzIvgWAppEbXy7Bd8kd8jCwD8RFJHB6Rg2+MRTAcaEjN/aHOwiw9NhETRyH3QUzGA0O5mIzGabd9ithDB2WSMd2U0fDCbjQt23mVNSXOwrcbQv/PwLei06pEnxJQifEB78ORQxDfTE1icIcq+Y5DR7GzUFecStZVUGPYNWuDr6mpRjg9dNGu4Jaqk3oSEk=
