sudo: required
language: python
python:
- '3.6'
addons:
  apt:
    packages:
    - bc
services:
- docker
env:
  global:
  - JQ_BINARY="https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64"
  - PATH="/usr/bin:$PATH"
  - AWS_DEFAULT_REGION="us-west-2"
  - TF_VAR_BUILD_NUMBER=${TRAVIS_JOB_NUMBER/./-}
  - secure: GBTo9IB6eDxA3pHpvt+kuKzxr92HmBrPwPqh+YXH7YqtqzwPhekC5jNOWjPogZG5KFLMcsJGtAgqxye33ICyeWKWR4y4q6obIOmq4f984QYBHHmv/Ll0ZwtaD3hy6E9mP8kteazawM+xgipQWE2wMKIUysMTpgqWGVWXqFoeApHCyG8MTJJ4N9Re8D+MuwXJigLZjWqcBbpvSPlCC1qa4cZ2fIxDBl5PdS92ZjUGyN11thDDmF67RFC49r/h6pycHRBG7N/5MQ69XWNZ8ZyBZtdRWooic8wc8sIpo0d/KCQJkTMi1LNs7RxVNo7KYI+Oky/r1B2mMT8gSCzS2wBm2HNl1sJVvYs6X2FAeEHj5SOYLsZMBm0HbHM3m61WZe7SJADWQ9nuddVR3UrFhw+j06gnBstKOdJXtsgxA3A0Nq42NJa8BxM3++FxQgm4OU2reRzW0gVEHFKiz6sNCGwSmcxJxphEK3E0sYKXKPWD2kMn1ERdTfgVrDrLmcby+77m4GXM5kiWJnZ2C5RHUY8ZueIEILHsDgj9VqF955smV/w1sugaJHitUjYyJ/UpD4+Yl0NeSnKb7ljm/9ZvgpHRsPlMGxiSi5y3zeqbf8XTwvJX8C9prLCh1S/lHffu+PERax/Dfa5vwKNJmKalKOJcC6vm4NsCTze/gr/PV6qGOmU=
  - secure: WdM7ZZD+t5/7LUsdGRbj9HalzlpS+n3GsPntU7xzXpQ79vZOlBGqry8OZWo17ES9wINzT3//2g9UyA/ok4vHgj/d93RBw+BSpCohYR4MOgcwpXqq3IF5eRtU5vsTV31ukOlMfSW5epqXF6qvs9B0bA1OYN2EB7F4r/gX2tvAM7mPERXrZ2QGTyz7L+LhiZMQD0G9ARNvycr5K/Qewdi1kkeoyO3zLHvysoXEWy/0E9CdeWr8Matt6QkG1e8cW/AZt0ms/Q70glhif7P8uMVU26rHQ6howTxmU4Sg8ZHMWoNf1z3FJWfjgfe+sq4fyssAQSY5oK0HyvnCe2hF4aTMCZcsZHtzUwpSDtgcHs328PGGr0Q0dg6dMpuCMBNd3P85XyhvBEl7QI4ccc50pW4+szokCSZqai9bPM9n8KCB0ebQUw4+byltEDf1rrXqWfYtDHxfDReePcxNTAM1hmsMvaT+uRa4cJH9XlKWsd8I/LzpV8GX9qtpBw+zct92WP2a9FN+6EaTHwW0edU8GvDnIpD8QOJcYrRBmXtUnBTLiJaa/QrA43YsyN9agr83QkOg/0liX9lQWyXodlr5yXnM99HO/lerCOjP1bszAHsj+0E369WrPx7FGrKOxBZCsMDVIyMGelBJeffYW4jnvdbD7HK/er90u8aMhqmxrmggP6M=
  - secure: b/cEC/ajDisfvSg+l72rhEtc3idCwIP2WnJljBXwasgf9YP7mRAS1WgfiCwV2cMucN4CUCBEaMwFoUj/Ugehc8CZiWvu2Sw3AS+s2XIFfGvsqQ6t8IFq9Xcd/An9QluU68N9V7srxCbBeQEC8OGoYivB5lkcyMH98AUi0FbjfT1UUulrNmg0C9JGKY9g89dKEFzlqEIJGXbQx1fFMQP7M5WVNiTJ/5aJS/aGFXiuleWv8l4mOOrDZ0U3Dz/TCzqBDPEfQlrlW98JMlxEtgfcGEqgNTHGD6cnmgfY+aUvj2q68smPh1cA9AaEQvXKvF5lXvyOh+kKKzqGTBT7D9sfNIzGCHn5RPbQqOGp7dEoDaOXXejmOI2jRv7qeTHqH+kOcA7ePHRbfBB48rQ3r7na3QO4LtWpd4NTBNEG2zG/5F4MEvsxhjSgwv/e2WCGIBcdWf0tT2EjiuMWt1xwTyylQM6cwWjnbabZYjfxbwHGDUogAMZrset7/wi9+9WGMTPAqhMz68UXzzr4jb8E9ncRmCvNRnsbeCeMA0MJxxQy0b+dikulXzgY4BHcNJZLdSj0l+3bY17OoxjG5e/1KPOfLNtSuZHgqlJpZyE1NwusiKLCz/QnhPdsjqIuypkRxBhsHaUBhJdotFvpmGLN6IMfqjMJ6IGbRC6WkY91Bfw4D2k=
  - secure: XppRGL9b8ilwXtfbhqDAiun99KoTN5fbLCI2iAsi0iKh6QPiLg5L6Us+NZfNg1dTZHeXTVAKDnU4DkyXRspHofM5AVlrPQdC0TD+GN6X1rtJPo50COTVkB9iKxsGkPV2JHKyH2tVnnR+Lpwc8Kbc/6wibGC2JA/98dK1YiZwD7SeROYirDFWhhTQYUOCPhZHck+UXOJMnU6lbt46Z8MZPxtkZyTmJLFGdPaYAHFcUbHLEBZOvEjj34HCko7mZEAzDneTPqdgBVFdKU0+BS1v72cXbhzIcGVWdWooXpz0WdTythlx9/UHK1aJCJ+JESYuAgaEz/MCzUsOX8ZIJXZKjmCHn6F+qC62NzZwVBDNd6n2CqHVQZI8Vuqz0gCHczv1h1rqxigTogn6o16ocj0Ts+YqGz6ZsLAZqx+T1CMS8LmUBH9mOnQv6IEG7NKdW7i9GiIxul3mwlZrfwxymU4C/GETiwFS4Eq2rUxXzzY8OZ6XpNSOkUw6kyufQmYkUGZGu/UXjUGJdECatszyld1z7SLDH2Vcd0dQ8MbCQBTWXKY3qxHww7XuiSeg/7kb2/xGRFragWpBtEFKfcaTitWX2VeeQtiec2q45QxxOM8HoP1CQpm1fT3G3/hz1G8DgpFoXCBaHWBDPZI8uAH9UaqJJyiRZXrLx51xzLTMm42x1vE=
before_install:
- pip install ansible==2.4.0.0 awscli --upgrade
- sudo apt-get update -qq
- sudo apt-get install -y -o Dpkg::Options::="--force-confnew" docker-ce
- gpg --keyserver ha.pool.sks-keyservers.net --recv-key 13F26F82E955B8B8CE469054F29CCEBC83FD4525
- mkdir -p ~/bin && curl -sSL -o ~/bin/jq $JQ_BINARY && chmod +x ~/bin/jq
- export PATH=$PATH:~/bin
- "./manage download-terraform"
- "./manage download-packer"
- "./manage download-restic"
matrix:
  include:
  - env: NAME="packet/device"
    script: "./manage test-terraform $NAME"
  - env: NAME="aws/fastmail"
    script: "./manage test-terraform $NAME"
  - env: NAME="aws/vpc"
    script: "./manage test-terraform $NAME"
  - env: NAME="aws/secure-store"
    script: "./manage test-terraform $NAME"
  - env: NAME="workstation/amazon-ebs"
    script: "./manage test-packer $NAME"
