---

- hosts: all
  gather_facts: no
  tasks:
    - name: "check if we can connect with {{ normalize_username }} user"
      local_action: >
        shell ssh \
        -o BatchMode=yes \
        -o ConnectTimeout=5 \
        -o StrictHostKeyChecking=no \
        -p "{{ ansible_port | default(22) }}" \
        "{{ normalize_username }}@{{ inventory_hostname }}" \
        exit
      register: normalize_check_user
      changed_when: normalize_check_user.rc == 0
      ignore_errors: yes
      no_log: true
      become: false

    - debug:
        var: normalize_check_user

    - name: set ansible ssh user to {{ normalize_username }}
      set_fact: ansible_user="{{ normalize_username }}"
      when: normalize_check_user is defined and normalize_check_user|changed
